import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class Tela extends javax.swing.JFrame {
ArrayList<PessoaFisica> listaPessoaFis;
ArrayList<PessoaJuridica> listaPessoaJur;

String tipo;
    /**
     * Creates new form Tela
     */
public void LoadTablePessoa(){
    int i;
    DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Tipo:","Nome:", "Documento:", "Email:","Telefone"},0);
    if(btn_PeFisica.isSelected()){
               tipo = "Fisica";
               for(i = 0;i<listaPessoaFis.size();i++){
       String nome = listaPessoaFis.get(i).getNome();
       String documento = listaPessoaFis.get(i).getDocumento();
       String email = listaPessoaFis.get(i).getEmail();
       String telefone = listaPessoaFis.get(i).getTelefone();
        modelo.addRow(new Object[]{nome,documento,email,telefone});
        tabela_PessoaJur.setModel(modelo);
        tabela_PessoaJur.getColumnModel();
}
           }else{
               tipo = "Juridica";
               for(i = 0;i<listaPessoaJur.size();i++){
       String nome = listaPessoaJur.get(i).getNome();
       String documento = listaPessoaJur.get(i).getDocumento();
       String email = listaPessoaJur.get(i).getEmail();
       String telefone = listaPessoaJur.get(i).getTelefone();
        modelo.addRow(new Object[]{nome,documento,email,telefone});
        tabela_PessoaJur.setModel(modelo);
        tabela_PessoaJur.getColumnModel();
}
           }
    
    }

    public Tela() {
        initComponents();
        setLocationRelativeTo(null);
        listaPessoaFis = new ArrayList();
        listaPessoaJur = new ArrayList();
        btn_Pessoa_Remover.setEnabled(true);
        btn_Pessoa_Salvar.setEnabled(true);
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_PessoaJur = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_Pessoa_Nome = new javax.swing.JLabel();
        lbl_Pessoa_Documento = new javax.swing.JLabel();
        lbl_Pessoa_Email = new javax.swing.JLabel();
        lbl_Pessoa_Telefone = new javax.swing.JLabel();
        txt_Pessoa_Email = new javax.swing.JTextField();
        btn_Pessoa_Salvar = new javax.swing.JButton();
        btn_Pessoa_Remover = new javax.swing.JButton();
        txt_Pessoa_Nome = new javax.swing.JTextField();
        txt_Pessoa_Documento = new javax.swing.JTextField();
        txt_Pessoa_Telefone = new javax.swing.JTextField();
        btn_PeFisica = new javax.swing.JRadioButton();
        btn_PeJuridica = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_PessoaFis = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabela_PessoaJur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome:", "CNPJ:", "email:", "Telefone:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_PessoaJur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_PessoaJurMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_PessoaJur);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados:"));

        lbl_Pessoa_Nome.setText("Nome:");

        lbl_Pessoa_Documento.setText("Documento:");

        lbl_Pessoa_Email.setText("Email:");

        lbl_Pessoa_Telefone.setText("Telefone:");

        btn_Pessoa_Salvar.setText("Salvar");
        btn_Pessoa_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Pessoa_SalvarActionPerformed(evt);
            }
        });

        btn_Pessoa_Remover.setText("Remover");
        btn_Pessoa_Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Pessoa_RemoverActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_PeFisica);
        btn_PeFisica.setText("Pessoa Fisica");

        buttonGroup1.add(btn_PeJuridica);
        btn_PeJuridica.setText("Pessoa Juridica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Pessoa_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(lbl_Pessoa_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Pessoa_Telefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_Pessoa_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Pessoa_Telefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_Pessoa_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Pessoa_Documento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txt_Pessoa_Nome, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_PeFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_PeJuridica)))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Pessoa_Remover)
                    .addComponent(btn_Pessoa_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_PeFisica)
                    .addComponent(btn_PeJuridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Pessoa_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Pessoa_Nome)
                    .addComponent(btn_Pessoa_Salvar))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Pessoa_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Pessoa_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Pessoa_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Pessoa_Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Pessoa_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Pessoa_Telefone)
                    .addComponent(btn_Pessoa_Remover))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tabela_PessoaFis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabela_PessoaFis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome:", "CPF:", "Email:", "Telefone:"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_PessoaFis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_PessoaFisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_PessoaFis);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Agenda de Contatos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btn_Pessoa_SalvarActionPerformed(java.awt.event.ActionEvent evt) {                                                  
         int i = 0;
        if(btn_PeFisica.isSelected()){
               tipo = "Fisica";
        String nome = listaPessoaFis.get(i).getNome();
        String documento = listaPessoaFis.get(i).getDocumento();
        String email = listaPessoaFis.get(i).getEmail();
        String telefone = listaPessoaFis.get(i).getTelefone();
        PessoaFisica p = new PessoaFisica(nome,documento,email,telefone);
        txt_Pessoa_Nome.setText("");
        txt_Pessoa_Documento.setText("");
        txt_Pessoa_Email.setText("");
        txt_Pessoa_Telefone.setText("");
        listaPessoaFis.add(p);
        LoadTablePessoa();
           }else{
               tipo = "Juridica";
        String nome = listaPessoaJur.get(i).getNome();
        String documento = listaPessoaJur.get(i).getDocumento();
        String email = listaPessoaJur.get(i).getEmail();
        String telefone = listaPessoaJur.get(i).getTelefone();
               PessoaJuridica p = new PessoaJuridica(nome,documento,email,telefone);
        txt_Pessoa_Nome.setText("");
        txt_Pessoa_Documento.setText("");
        txt_Pessoa_Email.setText("");
        txt_Pessoa_Telefone.setText("");
        listaPessoaJur.add(p);
        LoadTablePessoa(); 
           }
    }                                                 

    private void btn_Pessoa_RemoverActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        if(btn_PeFisica.isSelected()){
               tipo = "Fisica";
        int index = tabela_PessoaFis.getSelectedRow();
        if(index >= 0 && index < listaPessoaFis.size()){
          Pessoa p = listaPessoaFis.get(index);
          listaPessoaFis.remove(index);
          LoadTablePessoa();
        txt_Pessoa_Nome.setText("");
        txt_Pessoa_Documento.setText("");
        txt_Pessoa_Email.setText("");
        txt_Pessoa_Telefone.setText("");
        }else{
            int indexx = tabela_PessoaJur.getSelectedRow();
        if(indexx >= 0 && indexx < listaPessoaJur.size()){
          Pessoa p = listaPessoaJur.get(indexx);
          listaPessoaJur.remove(indexx);
          LoadTablePessoa();
        txt_Pessoa_Nome.setText("");
        txt_Pessoa_Documento.setText("");
        txt_Pessoa_Email.setText("");
        txt_Pessoa_Telefone.setText("");
        }
        }
        }
    }                                                  

    private void tabela_PessoaJurMouseClicked(java.awt.event.MouseEvent evt) {                                              
      int index = tabela_PessoaJur.getSelectedRow();
      if(index >= 0 && index < listaPessoaJur.size()){
        Pessoa p = listaPessoaJur.get(index);
        txt_Pessoa_Nome.setText(p.getNome());
        txt_Pessoa_Documento.setText(p.getDocumento());
        txt_Pessoa_Email.setText(p.getEmail());
        txt_Pessoa_Telefone.setText(p.getTelefone());
      }
    }                                             

    private void tabela_PessoaFisMouseClicked(java.awt.event.MouseEvent evt) {                                              
      int index = tabela_PessoaJur.getSelectedRow();
      if(index >= 0 && index < listaPessoaJur.size()){
        Pessoa p = listaPessoaJur.get(index);
        txt_Pessoa_Nome.setText(p.getNome());
        txt_Pessoa_Documento.setText(p.getDocumento());
        txt_Pessoa_Email.setText(p.getEmail());
        txt_Pessoa_Telefone.setText(p.getTelefone());
      }
    }                                             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton btn_PeFisica;
    private javax.swing.JRadioButton btn_PeJuridica;
    private javax.swing.JButton btn_Pessoa_Remover;
    private javax.swing.JButton btn_Pessoa_Salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lbl_Pessoa_Documento;
    private javax.swing.JLabel lbl_Pessoa_Email;
    private javax.swing.JLabel lbl_Pessoa_Nome;
    private javax.swing.JLabel lbl_Pessoa_Telefone;
    private javax.swing.JTable tabela_PessoaFis;
    private javax.swing.JTable tabela_PessoaJur;
    private javax.swing.JTextField txt_Pessoa_Documento;
    private javax.swing.JTextField txt_Pessoa_Email;
    private javax.swing.JTextField txt_Pessoa_Nome;
    private javax.swing.JTextField txt_Pessoa_Telefone;
    // End of variables declaration                   
}
